### ISSUE TITLE
What version of Python to use with this script?

### ISSUE THREAD

**Issue by krokodylowy** [gmbnomis/uboot-mdb-dump#3]
Current version of Python 3.6.0 for Windows fails with error

d:\temp>python uboot_mdb_to_image.py a.txt >a.bin
Traceback (most recent call last):
  File "uboot_mdb_to_image.py", line 34, in <module>
    data, ascii_data = line.split("    ", maxsplit = 1)
ValueError: not enough values to unpack (expected 2, got 1)

OK. Everything is OK.  Command used must be strict python uboot_mdb_to_image.py<a.txt>a.bin
Format of a.txt is the same as in readme.

**Comment by Theosakamg** [comment]
Same issue...
Python 3.5.3 for Debian Testing

python3 uboot_mdb_to_image.py < dump-TV-IP672PI.txt > dump.img
...
00f80000  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
Traceback (most recent call last):
  File "uboot_mdb_to_image.py", line 34, in <module>
    data, ascii_data = line.split("    ", maxsplit = 1)
ValueError: not enough values to unpack (expected 2, got 1)

but result is good ! (when the script crash the rest of the content is a same "ff" to the end)

**Comment by gmbnomis** [comment]
The script is very picky about it's input (to flag transmission errors). For example, there must be no empty lines at all. Can you locate the position in the input file where it crashes and have a look whether there is something unusual?

**Comment by SciLor** [comment]
The problem is, when the last line of the script is not 16 bytes long, you will get that error.

**Comment by Feehley** [comment]
Patch your log file to include excess bytes. I'll try to remember to add an append to it if the line is too short and issue a patch request
